server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jeongyong95/config-repository.git
          search-paths: static-config
          basedir: ./joojeongyong.configserver
          clone-on-start: true
